/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Placeholder } from "./Placeholder";
export * as factories from "./factories";
export { Placeholder__factory } from "./factories/Placeholder__factory";
